/*
*****************************************
*			Map Labels					*
*	by Hazel (hazel16 @ CivFanatics)	*
*****************************************
*/
--OPTIONS
DROP TABLE IF EXISTS ML_Options;
CREATE TABLE ML_Options (ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT default "none", Value VARIANT default 0, Description TEXT);

--ICON CHOICES TO DISPLAY IN PANEL
DROP TABLE IF EXISTS ML_IconFontTextures;
CREATE TABLE ML_IconFontTextures (IconFontTexture TEXT);
INSERT INTO ML_IconFontTextures (IconFontTexture)
SELECT 'ICON_FONT_TEXTURE_DEFAULT' UNION ALL
SELECT 'ICON_FONT_TEXTURE_EXPANSION2' UNION ALL
SELECT 'ICON_ML_MAP' UNION ALL
SELECT 'ICON_ML_MAP2';


--LABELS
DROP TABLE IF EXISTS ML_LabelFonts;
CREATE TABLE ML_LabelFonts(ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, Description TEXT, NeedsStyleFix INTEGER);
INSERT INTO ML_LabelFonts(Type,NeedsStyleFix)
SELECT 'TwCenMT14',1 UNION ALL
SELECT 'TwCenMT16',0 UNION ALL
SELECT 'TwCenMT18',1 UNION ALL
SELECT 'TwCenMT20',0 UNION ALL
SELECT 'TwCenMT22',1 UNION ALL
SELECT 'TwCenMT24',0 ;
UPDATE ML_LabelFonts
SET Description = 'TXT_KEY_ML_' || UPPER(Type);

DROP TABLE IF EXISTS ML_LabelFontStyles;
CREATE TABLE ML_LabelFontStyles(ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, Description TEXT);
INSERT INTO ML_LabelFontStyles(Type)
SELECT 'Base' UNION ALL
SELECT 'Shadow' UNION ALL
SELECT 'SoftShadow' UNION ALL
SELECT 'Stroke' ;
UPDATE ML_LabelFontStyles
SET Description = 'TXT_KEY_ML_' || UPPER(Type);

DROP TABLE IF EXISTS ML_LabelDisplayTypes;
CREATE TABLE  ML_LabelDisplayTypes(ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, Description TEXT);
INSERT INTO ML_LabelDisplayTypes(Type)
SELECT 'LABELDISPLAY_TEXTANDICON' UNION ALL
SELECT 'LABELDISPLAY_TEXTONLY' UNION ALL
SELECT 'LABELDISPLAY_ICONONLY' UNION ALL
SELECT 'LABELDISPLAY_DISABLED' ;
UPDATE ML_LabelDisplayTypes
SET Description = 'TXT_KEY_ML_' || Type;

DROP TABLE IF EXISTS ML_LabelMainTypes;
CREATE TABLE ML_LabelMainTypes(ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, Description TEXT, Icon TEXT,
	DisplayType TEXT, Font TEXT, FontStyle TEXT,
	Font_R REAL, Font_G REAL, Font_B REAL, Font_A REAL,
	Shadow_R REAL, Shadow_G REAL, Shadow_B REAL, Shadow_A REAL,
	Background_R REAL, Background_G REAL, Background_B REAL, Background_A REAL,
	Border_R REAL, Border_G REAL, Border_B REAL, Border_A REAL);
INSERT INTO ML_LabelMainTypes(Type,Icon,DisplayType,Font,FontStyle,
	Font_R, Font_G, Font_B, Font_A,
	Shadow_R, Shadow_G, Shadow_B, Shadow_A,
	Background_R, Background_G, Background_B, Background_A,
	Border_R, Border_G, Border_B, Border_A)
SELECT 'PLAYER','[ICON_TEAM_2]','LABELDISPLAY_TEXTANDICON',
	'TwCenMT18', 'Shadow',
	1,1,1,1, --Font
	0,0,0,1, --Shadow
	0,0,0,0.2, --Background
	1,0,0,0 --Border
	UNION ALL
SELECT 'REGION','[ICON_ML_WORLD]','LABELDISPLAY_TEXTONLY',
	'TwCenMT24', 'Base',
	1,1,1,1, --Font
	0,0,0,1, --Shadow
	0,0,0,0.2, --Background
	1,0,0,0 --Border
	UNION ALL
SELECT 'FEATURE','[ICON_ML_TREE]','LABELDISPLAY_TEXTONLY',
	'TwCenMT18', 'Stroke',
	1,1,1,1, --Font
	0,0,0,1, --Shadow
	0,0,0,0.2, --Background
	1,0,0,0 --Border
	UNION ALL
SELECT 'BATTLE','[ICON_WAR]','LABELDISPLAY_ICONONLY',
	'TwCenMT18', 'Shadow',
	1,1,1,1, --Font
	0,0,0,1, --Shadow
	0,0,0,0.2, --Background
	1,0,0,0 --Border
	;
UPDATE ML_LabelMainTypes
SET Description = 'TXT_KEY_ML_MAINTYPE_' || Type;

DROP TABLE IF EXISTS ML_LabelSubTypes;
CREATE TABLE ML_LabelSubTypes(ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, MainType TEXT, Description TEXT, Icon TEXT,
	Enabled BOOLEAN DEFAULT 1, MaxChunks INTEGER, MinPlotsInChunk INTEGER, MaxPlotsInChunk INTEGER, MinPlotDistance INTEGER);
INSERT INTO ML_LabelSubTypes(Type,MainType,Icon)
SELECT 'PLAYER', 'PLAYER', '[ICON_TEAM_2]' UNION ALL
SELECT 'REGION', 'REGION', '[ICON_ML_WORLD]' UNION ALL
SELECT 'OCEAN', 'REGION', '[ICON_ML_OCEAN]' UNION ALL
SELECT 'ISLAND', 'REGION', '[ICON_ML_COAST]' UNION ALL
SELECT 'MOUNTAIN', 'FEATURE', '[ICON_ML_MOUNTAIN]' UNION ALL
SELECT 'RIVER', 'FEATURE', '[ICON_ML_RIVER]' UNION ALL
SELECT 'LAKE', 'FEATURE', '[ICON_ML_LAKE]' UNION ALL
SELECT 'FOREST', 'FEATURE', '[ICON_ML_FOREST]' UNION ALL
SELECT 'DESERT', 'FEATURE', '[ICON_ML_DESERT]' UNION ALL
SELECT 'BATTLE', 'BATTLE', '[ICON_WAR]' UNION ALL
SELECT 'RAZED', 'BATTLE', '[ICON_RAZING]' ;
UPDATE ML_LabelSubTypes
SET Description = 'TXT_KEY_ML_SUBTYPE_' || Type;

UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=40,
	MinPlotDistance=0
WHERE Type='REGION';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=60,
	MinPlotDistance=0
WHERE Type='OCEAN';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=3,
	MaxPlotsInChunk=15,
	MinPlotDistance=5
WHERE Type='ISLAND';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=2,
	MinPlotDistance=5
WHERE Type='MOUNTAIN';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=3,
	MinPlotDistance=4
WHERE Type='RIVER';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=1,
	MinPlotDistance=5
WHERE Type='LAKE';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=4,
	MinPlotDistance=4
WHERE Type='FOREST';
UPDATE ML_LabelSubTypes SET
	MaxChunks=10000,
	MinPlotsInChunk=4,
	MinPlotDistance=4
WHERE Type='DESERT';



DROP TABLE IF EXISTS ML_Labels_Static;
CREATE TABLE ML_Labels_Static (ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, PlotX INTEGER, PlotY INTEGER, MainType TEXT default "FEATURE", SubType TEXT, ToolTip TEXT, Icon TEXT);

DROP TABLE IF EXISTS ML_Labels_Dynamic;
CREATE TABLE ML_Labels_Dynamic (ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, MainType TEXT default "FEATURE", SubType TEXT, CultureType TEXT);



--CULTURES
--CultureEras
DROP TABLE IF EXISTS ML_CultureEras;
CREATE TABLE ML_CultureEras (ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, Description TEXT);
INSERT INTO ML_CultureEras (Type)
SELECT 'ANY' UNION ALL
SELECT 'ANCIENT' UNION ALL
SELECT 'MODERN';

UPDATE ML_CultureEras
SET Description = 'TXT_KEY_ML_CULTURE_ERA_' || Type;

--CultureGroups
DROP TABLE IF EXISTS ML_CultureGroups;
CREATE TABLE ML_CultureGroups (ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, Description TEXT);
INSERT INTO ML_CultureGroups (Type)
SELECT 'CULTURE_GROUP_ASIAN' UNION ALL
SELECT 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'CULTURE_GROUP_PACIFIC' UNION ALL
SELECT 'CULTURE_GROUP_MIDEASTERN' UNION ALL
SELECT 'CULTURE_GROUP_AFRICAN' ;

UPDATE ML_CultureGroups
SET Description = 'TXT_KEY_ML_' || Type;

--Cultures
DROP TABLE IF EXISTS ML_Cultures;
CREATE TABLE ML_Cultures (ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT, 'Group' TEXT, Description TEXT, SuggestedCivs TEXT);
INSERT INTO ML_Cultures (Type, 'Group')
SELECT	'EAST_ASIAN', 'CULTURE_GROUP_ASIAN' UNION ALL
SELECT 'ARABIAN', 'CULTURE_GROUP_MIDEASTERN' UNION ALL
SELECT 'MEDITERRANEAN', 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'GERMANIC', 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'AFRICAN', 'CULTURE_GROUP_AFRICAN' UNION ALL
SELECT 'FIRST_AMERICANS', 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'BRITISH', 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'PACIFIC', 'CULTURE_GROUP_PACIFIC' UNION ALL
SELECT 'INDIAN', 'CULTURE_GROUP_ASIAN' UNION ALL
SELECT 'SLAVIC', 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'SPANISH', 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'PORTUGUESE', 'CULTURE_GROUP_EUROPEAN' UNION ALL
SELECT 'FRENCH', 'CULTURE_GROUP_EUROPEAN' UNION ALL

SELECT 'MOD_TP_AUSTRALIAN', 'CULTURE_GROUP_PACIFIC' UNION ALL
SELECT 'MOD_TP_CANADIAN', 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'MOD_TP_MESO_AMERICAN', 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'MOD_TP_SOUTH_AMERICAN', 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'MOD_TP_SOUTHEAST_ASIAN', 'CULTURE_GROUP_PACIFIC' UNION ALL

SELECT 'US_WESTERN', 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'US_SOUTHERN', 'CULTURE_GROUP_AMERICAN' UNION ALL
SELECT 'US_NORTHEAST', 'CULTURE_GROUP_AMERICAN' ;

UPDATE ML_Cultures
SET Description = 'TXT_KEY_ML_CULTURE_' || Type,
	SuggestedCivs = 'TXT_KEY_ML_CULTURE_' || Type || '_SUGGESTEDCIVS';

DROP TABLE IF EXISTS ML_CivCultures;
CREATE TABLE ML_CivCultures (ID INTEGER PRIMARY KEY AUTOINCREMENT, CivType TEXT, CultureType TEXT, CultureEra TEXT DEFAULT 'ANY');
INSERT INTO ML_CivCultures(CivType, CultureType, CultureEra)
SELECT 'CIVILIZATION_CHINA', 'EAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_KOREA', 'EAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MONGOL', 'EAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_SIAM', 'EAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_HUNS', 'EAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ARABIA', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_OTTOMAN', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PERSIA', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MOROCCO', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MOROCCO', 'FRENCH', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_ASSYRIA', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_BABYLON', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ROME', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_GREECE', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_CARTHAGE', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_VENICE', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_EGYPT', 'MEDITERRANEAN', 'ANCIENT' UNION ALL
SELECT 'CIVILIZATION_EGYPT', 'ARABIAN', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_BYZANTIUM', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_BYZANTIUM', 'SLAVIC', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_BYZANTIUM', 'ARABIAN', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_GERMANY', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_SWEDEN', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_DENMARK', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_AUSTRIA', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_NETHERLANDS', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_POLAND', 'SLAVIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ENGLAND', 'BRITISH', 'ANY' UNION ALL
SELECT 'CIVILIZATION_AMERICA', 'US_WESTERN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_AMERICA', 'US_SOUTHERN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_AMERICA', 'US_NORTHEAST', 'ANY' UNION ALL
SELECT 'CIVILIZATION_CELTS', 'BRITISH', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ZULU', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ETHIOPIA', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ETHIOPIA', 'ARABIAN', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_SONGHAI', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_JAPAN', 'PACIFIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_POLYNESIA', 'PACIFIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_POLYNESIA', 'BRITISH', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_INDONESIA', 'MOD_TP_SOUTHEAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_INDIA', 'INDIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_SPAIN', 'SPANISH', 'ANY' UNION ALL
SELECT 'CIVILIZATION_RUSSIA', 'SLAVIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PORTUGAL', 'PORTUGUESE', 'ANY' UNION ALL
SELECT 'CIVILIZATION_BRAZIL', 'PORTUGUESE', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_BRAZIL', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_FRANCE', 'FRENCH', 'ANY' UNION ALL
SELECT 'CIVILIZATION_IROQUOIS', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_IROQUOIS', 'US_NORTHEAST', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_AZTEC', 'FIRST_AMERICANS', 'ANCIENT' UNION ALL
SELECT 'CIVILIZATION_AZTEC', 'MOD_TP_MESO_AMERICAN', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_MAYA', 'FIRST_AMERICANS', 'ANCIENT' UNION ALL
SELECT 'CIVILIZATION_MAYA', 'MOD_TP_MESO_AMERICAN', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_INCA', 'FIRST_AMERICANS', 'ANCIENT' UNION ALL
SELECT 'CIVILIZATION_INCA', 'MOD_TP_SOUTH_AMERICAN', 'MODERN' UNION ALL
SELECT 'CIVILIZATION_SHOSHONE', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_SHOSHONE', 'US_WESTERN', 'MODERN' UNION ALL
--modded civs
--TPangolin's civilizations
SELECT 'CIVILIZATION_COLONIALAUSTRALIA', 'MOD_TP_AUSTRALIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_COLONIALCANADA', 'MOD_TP_CANADIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MEXICOREPUBLIC', 'MOD_TP_MESO_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_JFD_PHILIPPINES', 'MOD_TP_SOUTHEAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_BLACKFOOTFIRSTNATION', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_DENEFIRSTNATION', 'MOD_TP_CANADIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_BOER', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_VIETNAM', 'MOD_TP_SOUTHEAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_CLINUIT', 'MOD_TP_CANADIAN', 'ANY' UNION ALL
--tarcisiocm's civilizations
SELECT 'CIVILIZATION_TCM_ETRUSCAN', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TCM_SICILY', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TCM_PTOLEMAIC', 'MEDITERRANEAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TCM_HRE', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_GREATEREUROPE_GERMANY', 'GERMANIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TCM_SUEBI', 'SPANISH', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PARTHIA', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TCM_BACTRIA', 'INDIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TCM_ALAN', 'EAST_ASIAN', 'ANY' UNION ALL
--Leugi's civilizations
SELECT 'CIVILIZATION_LEUGI_CUBA', 'MOD_TP_MESO_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TROPICO', 'MOD_TP_MESO_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_QULLANA', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MUISCA', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MAPUCHE', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TUPI', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TIWANAKU', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_ARGENTINA', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_BOLIVIA', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_CHILE', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_GRANCOLOMBIA', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PARAGUAY', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PERU', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_LEUGI_ISRAEL', 'ARABIAN', 'ANY' UNION ALL
--Gedemo's civilizations
SELECT 'CIVILIZATION_SAMOYED', 'EAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_SAMOYED', 'SLAVIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_NUBIA', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_NUBIA', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MAASAI', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_TIMURIDE', 'ARABIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PAPUA', 'PACIFIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_PAPUA', 'MOD_TP_SOUTHEAST_ASIAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_MONOMOTAPA', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_KUHIKUGU', 'MOD_TP_SOUTH_AMERICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_KANEM', 'AFRICAN', 'ANY' UNION ALL
SELECT 'CIVILIZATION_YUPIK', 'SLAVIC', 'ANY' UNION ALL
SELECT 'CIVILIZATION_CARIB', 'FIRST_AMERICANS', 'ANY' UNION ALL
SELECT 'CIVILIZATION_CHACHAPOYAS', 'MOD_TP_SOUTH_AMERICAN', 'ANY' ;